<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AeroAscent.Core.Dominio</RootNamespace>
    <AssemblyName>AeroAscent.Core.Dominio</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

</Project>
